#%RAML 1.0 DataType
type: array
items:
  properties:
      title: string
      runtime: number
      format: string
      plot: string
      releaseYear: number
      releaseMonth: number
      releaseDay: number